# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/My_31CPU_post/My_31CPU_post.cache/wt [current_project]
set_property parent.project_path D:/My_31CPU_post/My_31CPU_post.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files D:/mips_31_mars_simulate.coe
add_files d:/cpu312023.coe
add_files -quiet D:/My_31CPU_post/My_31CPU_post.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp
set_property used_in_implementation false [get_files D:/My_31CPU_post/My_31CPU_post.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp]
read_verilog -library xil_defaultlib {
  D:/My_31CPU_post/My_31CPU_post.srcs/sources_1/new/ALU.v
  D:/My_31CPU_post/My_31CPU_post.srcs/sources_1/new/PC.v
  D:/My_31CPU_post/My_31CPU_post.srcs/sources_1/new/Decoder.v
  D:/My_31CPU_post/My_31CPU_post.srcs/sources_1/new/Controler.v
  D:/My_31CPU_post/My_31CPU_post.srcs/sources_1/new/regfile.v
  D:/My_31CPU_post/My_31CPU_post.srcs/sources_1/new/IMEM.v
  D:/My_31CPU_post/My_31CPU_post.srcs/sources_1/new/DMEM.v
  D:/My_31CPU_post/My_31CPU_post.srcs/sources_1/new/CPU.v
  D:/My_31CPU_post/My_31CPU_post.srcs/sources_1/new/Divider.v
  D:/My_31CPU_post/My_31CPU_post.srcs/sources_1/new/seg7x16.v
  D:/My_31CPU_post/My_31CPU_post.srcs/sources_1/new/sccomp_dataflow.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top sccomp_dataflow -part xc7a100tcsg324-1


write_checkpoint -force -noxdef sccomp_dataflow.dcp

catch { report_utilization -file sccomp_dataflow_utilization_synth.rpt -pb sccomp_dataflow_utilization_synth.pb }
